presence: fix for TestRealtimePresence* tests
Stress testing TestRealtimePresence* suite fails occasionally with:

--- FAIL: TestRealtimePresence_Sync (3.85s)
        realtime_presence_test.go:55: clientID="client_bool" not found in presence map

The reason was buggy sync check condition which did not cover scenario
where sync flag was missing but sync serial present.

Test failures were reproduced with:

$ go get golang.org/x/tools/cmd/stress
$ stress ./ably.test -test.run TestRealtimePresence