Use fake time in RTN23 test.
Previous way was flaky due to the artificially short timeouts:

--- FAIL: TestRealtimeConn_RTN23 (0.00s)
    realtime_conn_spec_test.go:1764: [ErrorInfo :timeout code=80003 disconnected statusCode=0] See https://help.ably.io/error/80003